# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH

# # Get the aliases and functions
# if [ -f ~/.aliases ]; then
#   . ~/.aliases
# fi

# export EDITOR="nvim"
export EDITOR=nvim

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes

# ZSH_THEME="clean"
ZSH_THEME="jonathan"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)

# User configuration

export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='nvim'
else
  export EDITOR='vim'
fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# To avoid ranger loading conf twice
export RANGER_LOAD_DEFAULT_RC=false

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.

alias S='source ~/.zshrc'
alias ra='ranger'
alias lg='lazygit'
alias neo='neofetch'
alias nv='nvim'
alias neo='neofetch'
alias sudo='sudo '
alias X='chmod +x'
alias rc='nvim ~/.zshrc'
alias nvrc='nvim ~/github/mydotfiles/nvim/init.vim'
alias c='clear'
alias a='~'
alias e='exit'

alias upd='sudo pacman -Syyu'
alias pac='sudo pacman'
alias ins='sudo pacman -S'

# docker
alias dk='sudo docker'
alias dkr='sudo docker run'

alias dkps='sudo docker ps'
alias dkpa='sudo docker ps -a'
alias dkpq='sudo docker ps -aq'  # conteiner ID

alias dksto='sudo docker stop'
alias dksta='sudo docker start'

alias dkimg='sudo docker images'
alias dkrmi='sudo docker rmi'

alias dkrm='sudo docker rm' # remove container
# or dksto $(dkpq)  # delete all container

alias dkvol='sudo docker volume'

# docker compose
alias dkc='sudo docker compose'
alias dkcb='sudo docker compose --build'
alias dkcu='sudo docker compose up -d'
alias dkcd='sudo docker compose down'
alias dkcp='sudo docker compose ps'
alias dkcr='sudo docker compose run'
alias dkcs='sudo docker compose stop'

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
    aliases
    ag
    git
    wd
    #web-search
    zsh-autosuggestions
    zsh-syntax-highlighting
)

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
source $ZSH/oh-my-zsh.sh



